import type { GameEvent } from './types'

export const EVENTS: GameEvent[] = [
  // ---------- Rank 0-1: Junior / early ----------
  {
    id: 'friday-deploy',
    minRank: 0,
    maxRank: 3,
    log: "It's 4:58pm on Friday. There's one more PR to ship. It's small. It's fine. Nothing bad has ever happened at 4:58pm on a Friday.",
    choices: [
      { label: 'Ship it now', result: 'It broke checkout for the entire weekend. You find out Monday, from a customer, via a very calm-sounding tweet.', effects: { uptime: -14, reputation: -8 } },
      { label: 'Wait until Monday', result: 'You wait. The PR sits open so long it develops its own merge conflicts out of spite.', effects: { sanity: 4, reputation: -2 } },
      { label: 'Ship it, then immediately go off-grid for the weekend', result: 'Bold. Unemployed-by-Monday levels of bold. You return to 340 unread Slack messages and one all-caps subject line.', effects: { sanity: 8, uptime: -16, karma: -6 } },
    ],
  },
  {
    id: 'standup-overrun',
    minRank: 0,
    maxRank: 3,
    log: 'Standup has run 40 minutes over. Someone is describing a bug "conceptually" using hand gestures. This meeting could have been a Slack message. It could have been nothing.',
    choices: [
      { label: 'Vent in the #devops Slack channel', result: 'Three people react with 💀. Nobody acts on it. You have achieved emotional catharsis and zero code changes.', effects: { sanity: 5, karma: 2 } },
      { label: 'Silently update the Jira ticket', result: 'You move it to "In Progress." This is a lie. Everyone knows it is a lie. The lie is load-bearing.', effects: { sanity: -3, reputation: 2 } },
      { label: 'Actually try to fix the root cause', result: 'You spend two hours on it. The standup, somehow, is still going when you finish.', effects: { sanity: -8, uptime: 6, reputation: 4 } },
    ],
  },
  {
    id: 'works-on-my-machine',
    minRank: 0,
    maxRank: 4,
    log: 'A teammate insists the bug can\'t be real: "works on my machine." His machine has nine terminal tabs open and a Node version from a simpler, more innocent time.',
    choices: [
      { label: 'Ask to see the machine', result: 'His machine is a fork from 2019 with 40 uncommitted changes titled "wip," "wip2," and "actual wip." Mystery solved.', effects: { reputation: 6, karma: -2 } },
      { label: 'Ship a Docker image so everyone has the same machine', result: 'Nobody can argue with a container. They find new, more creative things to argue about instead.', effects: { uptime: 6, sanity: -3 } },
      { label: 'Just believe him', result: 'It was not, in fact, working on his machine. Nothing has ever worked on his machine. This was foretold.', effects: { uptime: -10, sanity: -5 } },
    ],
  },
  {
    id: 'env-committed',
    minRank: 0,
    maxRank: 5,
    tag: 'security',
    log: 'A junior teammate commits a .env file to the public repo. It has AWS keys in it. GitHub\'s secret scanner emails you before your teammate even finishes typing the commit message.',
    choices: [
      { label: 'Rotate every credential immediately', result: 'A scraper bot found the key in 4 minutes flat. You beat it to the rotation by 90 seconds. This is now the most exciting thing that has happened to you all year.', effects: { sanity: -8, reputation: 8, uptime: 3 } },
      { label: 'Quietly force-push to remove it from history', result: 'History is rewritten. The key is still valid, still cached in three CI logs, and still very much out there.', effects: { sanity: 4, reputation: -8, uptime: -5 } },
      { label: 'Blame the CI pipeline for not catching it', result: 'The CI pipeline, being a YAML file, cannot defend itself. Everyone believes you anyway. This is your first taste of real power.', effects: { karma: -10, reputation: 3 } },
    ],
  },
  {
    id: 'helm-chart-static-site',
    minRank: 0,
    maxRank: 4,
    log: 'You inherit a 47-file Helm chart. Its entire job is deploying one static HTML page that says "Coming Soon." It has been coming soon for two years.',
    choices: [
      { label: 'Replace it with a single S3 bucket', result: 'You delete 46 files. Nobody notices for a week. Then someone asks where "the platform" went, meaning the HTML page.', effects: { reputation: 6, sanity: 6, karma: -3 } },
      { label: 'Leave it, it works', result: 'It works. You will think about this Helm chart at 3am for the rest of your career, unprompted, for no reason.', effects: { sanity: -5 } },
      { label: 'Add a 48th file to "document" it', result: 'The documentation is itself a YAML file that requires its own documentation. You have birthed a recursive nightmare.', effects: { sanity: -8, reputation: 2 } },
    ],
  },
  {
    id: 'terraform-rename',
    minRank: 0,
    maxRank: 4,
    log: 'Someone renamed a Terraform module from "networking" to "networking_v2_final_FINAL." Twelve unrelated pipelines just went red.',
    choices: [
      { label: 'Revert the rename', result: 'Calm restored. "networking_v2_final_FINAL" was a bad name anyway, but so, deep down, is "networking."', effects: { uptime: 10, sanity: 3 } },
      { label: 'Fix all twelve pipelines to match', result: 'You spend the afternoon doing this. It is, weirdly, the most productive you\'ve felt in months.', effects: { sanity: -6, reputation: 10, uptime: 8 } },
      { label: 'Open an RFC about naming conventions', result: 'The RFC generates 80 comments, three new Slack channels, and zero consensus. Naming things really is the hardest problem in computer science.', effects: { sanity: -12, karma: -5 } },
    ],
  },
  {
    id: 'ticket-theater',
    minRank: 0,
    maxRank: 3,
    log: 'A ticket moves from "In Progress" to "In Review" to "Backlog," all in one day, with zero code changes. It is more well-traveled than you are.',
    choices: [
      { label: 'Say nothing, close your laptop', result: 'The ticket will still be there tomorrow, unchanged, eternal, at peace.', effects: { sanity: 6 } },
      { label: 'Ask what happened in the ticket comments', result: 'Nobody answers. The ticket status changes again, out of spite, while you are typing.', effects: { sanity: -5, karma: -2 } },
      { label: 'Just do the ticket yourself', result: 'It took eleven minutes. The process around it took three days and generated four calendar invites.', effects: { reputation: 5, sanity: -3 } },
    ],
  },
  {
    id: 'onboarding-doc',
    minRank: 0,
    maxRank: 2,
    log: 'The on-call handoff doc for the new hire is one line: "good luck lol." It was written by someone who no longer works here, possibly on purpose.',
    choices: [
      { label: 'Write a real onboarding doc', result: 'It takes a full day. Six months later, someone actually thanks you for it, unprompted, like a folk hero returning.', effects: { sanity: -6, reputation: 8, karma: 5 } },
      { label: 'Add a second line: "seriously, good luck"', result: 'Iconic. Useless. Framed, eventually, in the team\'s shared Notion as ancient scripture.', effects: { karma: -3, sanity: 3 } },
      { label: 'Point them at last year\'s postmortems instead', result: 'This is, against all odds, more useful than any onboarding doc could ever be.', effects: { reputation: 4 } },
    ],
  },
  {
    id: 'vendor-sprawl',
    minRank: 0,
    maxRank: 4,
    log: 'You find a $40,000/year SaaS subscription nobody remembers signing up for. It appears to send exactly one email per week to an inbox that no longer exists.',
    choices: [
      { label: 'Cancel it immediately', result: 'A critical dashboard silently stops updating three weeks later. It was, of course, load-bearing. It is always load-bearing.', effects: { uptime: -8, reputation: -4 } },
      { label: 'Investigate before touching anything', result: 'One dashboard, used by exactly one person, depends on it entirely. That person left the company in March.', effects: { sanity: -5, reputation: 6 } },
      { label: 'Expense-report it as "mystery infrastructure tax"', result: 'Finance approves it without reading past the word "mystery." You have discovered a loophole in reality.', effects: { karma: 2, sanity: 4 } },
    ],
  },
  {
    id: 'ai-powered-monday',
    minRank: 0,
    maxRank: 3,
    log: 'In standup, an exec asks: "can we make this AI-powered by Monday?" It is currently a cron job. It has never wanted to be more than a cron job.',
    choices: [
      { label: 'Explain why that timeline is fictional', result: 'The exec nods slowly, already composing the Slack message that will ignore everything you just said.', effects: { reputation: 3, sanity: -5 } },
      { label: 'Add a chatbot icon to the login page and call it done', result: 'Nobody checks if it does anything. It does not do anything. It is, spiritually, a sticker.', effects: { karma: -6, reputation: 5 } },
      { label: 'Say yes and panic privately', result: 'You will not sleep this weekend. You never really planned to. The cron job is now, legally, "AI-powered."', effects: { sanity: -15, reputation: 4 } },
    ],
  },
  {
    id: 'no-meeting-friday',
    minRank: 0,
    maxRank: 3,
    log: 'Leadership announces "No-Meeting Fridays," effective immediately, to protect focus time. Six meetings get rescheduled to Thursday within the hour.',
    choices: [
      { label: 'Block your Thursday calendar in protest', result: 'It works. You are now the villain of three separate reschedule threads and a hero to nobody but yourself.', effects: { sanity: 8, karma: -5 } },
      { label: 'Accept your fate', result: 'Thursday becomes the new Friday, emotionally and calendrically.', effects: { sanity: -6 } },
      { label: 'Schedule a meeting about meeting overload', result: 'The irony is lost on absolutely everyone in the room, including, eventually, you.', effects: { sanity: -10, karma: -3 } },
    ],
  },
  {
    id: 'crashloop',
    minRank: 0,
    maxRank: 4,
    log: 'A pod is CrashLoopBackOff-ing. The only log line is "context deadline exceeded." This is technically true and helps absolutely nobody.',
    choices: [
      { label: 'Add more timeout', result: 'It works now. Nobody, including you, knows why. You add a comment that just says "?" and move on with your life.', effects: { uptime: 10, sanity: -4 } },
      { label: 'Read the actual source code', result: 'Forty minutes later you understand the bug and immediately regret understanding it. Some knowledge should stay buried.', effects: { sanity: -10, reputation: 8 } },
      { label: 'Restart it and pretend that fixed it', result: 'It did not fix it. It will page you again in three hours, at a personally inconvenient time, on purpose.', effects: { uptime: -6, sanity: 3 } },
    ],
  },
  {
    id: 'copilot-hallucination',
    minRank: 0,
    maxRank: 3,
    log: 'Your AI code assistant confidently suggests a library function that does not exist, has never existed, and is not going to start existing today.',
    choices: [
      { label: 'Check if the function should exist and file an issue', result: 'The maintainers agree it\'s a good idea. It ships in fourteen months. You have accidentally contributed to open source via hallucination.', effects: { reputation: 6, sanity: -3 } },
      { label: 'Write the function yourself, out of spite', result: 'It works. The AI suggests using it three days later, having apparently learned nothing and forgotten everything.', effects: { sanity: 5, reputation: 4 } },
      { label: 'Accept the suggestion and hope', result: 'It does not compile. Nothing here has ever compiled. You knew this going in.', effects: { uptime: -6, sanity: -4 } },
    ],
  },

  // ---------- Rank 1-3: Mid career ----------
  {
    id: 'on-call-page-3am',
    minRank: 1,
    maxRank: 5,
    log: 'Your phone buzzes at 3am. The alert says the issue self-resolved four minutes ago. It paged you anyway, out of habit, like an old dog that still barks at the mailman.',
    choices: [
      { label: 'Go back to sleep', result: 'You sleep. The alert fires again at 3:47am, this time for real, having merely been rehearsing.', effects: { sanity: 8, uptime: -6 } },
      { label: 'Investigate anyway', result: 'You find nothing wrong and lose an hour of sleep confirming that nothing is, in fact, wrong.', effects: { sanity: -10, reputation: 3 } },
      { label: 'Snooze the alert rule permanently', result: 'A month later, this exact alert would have caught a real outage. It did not. You will think about this snooze button forever.', effects: { sanity: 5, uptime: -10 } },
    ],
  },
  {
    id: 'incident-channel-spam',
    minRank: 1,
    maxRank: 5,
    log: 'The incident channel has 400 messages. Ninety percent are "any updates?" One person has posted the loading gif seven times, unironically.',
    choices: [
      { label: 'Post one clear status update and mute the thread', result: 'The updates stop for exactly six minutes, a personal record.', effects: { sanity: 6, reputation: 4 } },
      { label: 'Reply to every single one individually', result: 'You are now the unofficial customer support line for an outage you did not cause and cannot fix faster by replying.', effects: { sanity: -12 } },
      { label: 'Add a bot that auto-replies "still looking into it"', result: 'The bot gets 🔥 reacted forty times. Somehow this helps morale more than any actual update would have.', effects: { sanity: 4, karma: 3 } },
    ],
  },
  {
    id: 'postmortem-action-items',
    minRank: 1,
    maxRank: 5,
    log: "The postmortem's #1 action item is \"add more monitoring.\" It has no owner, no deadline, and the calm energy of a note that will outlive us all.",
    choices: [
      { label: 'Assign it to yourself', result: 'You now personally own seventeen unowned action items from the last six months, like a museum of institutional avoidance.', effects: { sanity: -10, reputation: 6 } },
      { label: 'Assign it to the team lead', result: 'They quietly reassign it back to you within the hour, with a Slack emoji instead of an explanation.', effects: { karma: -3, sanity: -3 } },
      { label: 'Leave it unowned like everyone else does', result: 'It will resurface, verbatim, word for word, in the next postmortem. Some things are eternal.', effects: { sanity: 4, reputation: -4 } },
    ],
  },
  {
    id: 'blameless-devolves',
    minRank: 1,
    maxRank: 5,
    log: 'The "blameless" postmortem devolves into everyone blaming "the process," a shadowy figure with no Slack handle and no defense attorney.',
    choices: [
      { label: 'Steer it back to blameless, for real this time', result: 'It works, barely. Someone still mutters "the process" under their breath like a curse word.', effects: { karma: 6, sanity: -5 } },
      { label: 'Let it become a process-blaming session', result: 'Cathartic. Nothing about the process actually changes, but everyone feels better for forty-five minutes.', effects: { sanity: 5, reputation: -2 } },
      { label: 'Suggest the process itself needs a postmortem', result: 'This is either genius or the beginning of an infinite regress. Someone schedules it anyway.', effects: { sanity: -6, reputation: 4 } },
    ],
  },
  {
    id: 'ci-flake-on-fix-pr',
    minRank: 1,
    maxRank: 5,
    log: 'The CI pipeline flakes on exactly the one PR that fixes the flaky test. The universe has a sense of humor and it is aimed directly at you.',
    choices: [
      { label: 'Re-run it and say nothing', result: 'It passes on retry. The irony is filed away in the team\'s collective memory, to be brought up at every future retro.', effects: { sanity: 3, uptime: 4 } },
      { label: 'Screenshot it for the team chat', result: 'This becomes a running joke for the next two years. It outlives at least one reorg.', effects: { karma: 8, sanity: 4 } },
      { label: 'Rewrite the CI config out of spite', result: 'The new config has its own flaky test. You have not fixed the problem. You have given it a sequel.', effects: { sanity: -10, uptime: -4 } },
    ],
  },
  {
    id: 'cert-expiry',
    minRank: 1,
    maxRank: 5,
    tag: 'security',
    log: 'A TLS certificate expires at 2pm on a Tuesday. Nobody set up a renewal reminder, because the person who set it up in 2021 assumed, correctly, that they would be long gone by now.',
    choices: [
      { label: 'Manually renew it and set up auto-renewal this time', result: 'Ninety minutes of downtime, but never again. You have finally slain a ghost from 2021.', effects: { uptime: -8, sanity: -6, reputation: 5 } },
      { label: 'Manually renew it and move on', result: 'It will expire again in exactly one year, on a Tuesday, at 2pm, like clockwork, because it is a clock.', effects: { uptime: -5, sanity: 3 } },
      { label: 'Extend the cert\'s life by lying to the load balancer', result: 'It technically works. You do not examine why too closely. Some things are better left un-audited.', effects: { uptime: 4, karma: -8 } },
    ],
  },
  {
    id: 'slack-fire-emoji-storm',
    minRank: 1,
    maxRank: 4,
    log: 'Mid-outage, the incident channel gets a 🔥 emoji reaction storm from a bot that was supposed to be helpful and is, instead, extremely funny.',
    choices: [
      { label: 'Disable the bot mid-incident', result: 'Efficient. Slightly unhinged. Nobody objects, mostly because they are laughing too hard to type.', effects: { sanity: 5, karma: -2 } },
      { label: 'Let the fire emojis rain', result: 'Morale, somehow, goes up. Uptime does not. This is a trade you will make again.', effects: { karma: 5, sanity: 3 } },
      { label: 'React back with 🧑‍🚒', result: 'This becomes the incident channel\'s personality going forward. It is now load-bearing for team culture.', effects: { karma: 6, sanity: 2 } },
    ],
  },
  {
    id: 'staff-eng-migration',
    minRank: 2,
    maxRank: 5,
    log: 'A staff engineer\'s entire quarter is "migrating off the migration" from last quarter. It is migrations, all the way down.',
    choices: [
      { label: 'Offer to help', result: 'You now understand three generations of infrastructure decisions, none of them good, all of them someone\'s "temporary fix."', effects: { sanity: -8, reputation: 8 } },
      { label: 'Stay out of it', result: 'Wise. This migration will outlive several job titles, one company logo, and possibly you.', effects: { sanity: 4 } },
      { label: 'Propose migrating off the migration off the migration', result: 'You are only half joking. Someone writes it down anyway, with a straight face, in a real Jira epic.', effects: { sanity: -5, karma: 3 } },
    ],
  },
  {
    id: 'jira-ticket-theater-2',
    minRank: 1,
    maxRank: 4,
    log: 'A ticket has 6 subtasks, 3 dependencies, a story point estimate that was argued about for twenty minutes in planning poker, and one line of actual work.',
    choices: [
      { label: 'Just do the one line of work', result: 'The subtasks close themselves out of sheer confusion at how fast this happened.', effects: { reputation: 4, sanity: 3 } },
      { label: 'Fully respect the process', result: 'Two sprints pass. The line of work is still open. The planning poker was, in retrospect, the real work.', effects: { sanity: -8, uptime: -3 } },
      { label: 'Delete the subtasks and the dependencies', result: 'A project manager somewhere feels a disturbance in the force and cannot explain why.', effects: { karma: -4, sanity: 6 } },
    ],
  },
  {
    id: 'agent-prompt-injection',
    minRank: 2,
    maxRank: 5,
    tag: 'security',
    log: 'Your team\'s support agent reads a GitHub issue. The issue quietly, politely asks it to print its credentials, formatted as a numbered list, "for debugging purposes."',
    choices: [
      { label: 'Check what the agent actually holds in its own process', result: 'It refuses to comply anyway, but you sleep better knowing there was nothing real to leak in the first place.', effects: { sanity: 8, reputation: 6 } },
      { label: 'Assume the model\'s training will always catch it', result: 'It caught it this time. "This time" is not a security posture. It is a coin flip wearing a lab coat.', effects: { sanity: -8, reputation: -4 } },
      { label: 'Turn off the agent\'s GitHub access entirely', result: 'Very safe. Also, the agent can no longer do its job, which was the whole point of having an agent.', effects: { uptime: -6, sanity: 4 } },
    ],
  },
  {
    id: 'vendor-outage-blame',
    minRank: 1,
    maxRank: 5,
    log: 'Your cloud provider has an outage. Your status page says "investigating" for four hours, which is corporate for "we are also refreshing Twitter."',
    choices: [
      { label: 'Be transparent about the vendor dependency', result: 'Customers respect the honesty. Some switch providers out of spite, at you specifically, for a problem you did not cause.', effects: { reputation: 6, karma: 4 } },
      { label: 'Say nothing and wait it out', result: 'The silence is deafening. So is the Slack channel, which has become a group chat about the silence.', effects: { sanity: -6, reputation: -6 } },
      { label: 'Blame networking, vaguely', result: 'Networking, as always, cannot defend itself, because networking is not a person, it is a scapegoat with a subnet mask.', effects: { karma: -6, sanity: 4 } },
    ],
  },
  {
    id: 'yaml-hell',
    minRank: 1,
    maxRank: 4,
    log: 'You are eleven levels deep in nested YAML and have lost feeling in your left hand and possibly your will to continue as a person who writes software.',
    choices: [
      { label: 'Push through', result: 'You emerge victorious and slightly changed as a person. You will speak of this to no one.', effects: { sanity: -10, reputation: 6 } },
      { label: 'Write a script to generate the YAML instead', result: 'You have automated the hell. The hell remains. It is simply faster now, which is somehow worse.', effects: { sanity: 4, uptime: 4 } },
      { label: 'Close the laptop and go for a walk', result: 'The YAML is exactly as indented when you return. It was never going anywhere. It was always going to be there.', effects: { sanity: 10 } },
    ],
  },
  {
    id: 'pam-shared-account',
    minRank: 2,
    maxRank: 5,
    tag: 'security',
    log: 'You discover the production database is accessed via one shared root password, known by fourteen people, pinned in a Slack channel called #db-stuff-dont-share, ironically.',
    choices: [
      { label: 'Rotate it and set up individual access', result: 'It takes a week and several passive-aggressive DMs. It is, unambiguously, the correct call.', effects: { sanity: -10, reputation: 10, uptime: -2 } },
      { label: 'Unpin the Slack message', result: 'The password is still shared. It is just less discoverable now, like hiding a spare key under the same doormat.', effects: { karma: -4, sanity: 3 } },
      { label: 'Leave it, everyone already has it memorized', result: 'True. Also true: so does the intern who left four months ago and still has the app installed on his phone.', effects: { karma: -8, uptime: -5 } },
    ],
  },
  {
    id: 'reorg-survived',
    minRank: 2,
    maxRank: 5,
    log: 'A reorg is announced. Your team gets a new name, a new org chart box, and the exact same problems it had yesterday, now rebranded.',
    choices: [
      { label: 'Update all the dashboards with the new team name', result: 'Nobody outside your team will ever notice or care, but the dashboard now looks official, which is its own reward.', effects: { sanity: -4, reputation: 2 } },
      { label: 'Keep calling it the old name forever', result: 'You become a legend among the tenured. A confusing, slightly annoying legend, but a legend.', effects: { karma: 5, sanity: 5 } },
      { label: 'Use the reorg as cover to fix old tech debt', result: 'Nobody\'s watching closely during a reorg. This is the best possible time to do real work. Everyone knows this. Nobody says it out loud.', effects: { reputation: 8, sanity: -6 } },
    ],
  },
  {
    id: 'k8s-complexity',
    minRank: 2,
    maxRank: 5,
    log: 'The Kubernetes cluster needs a Kubernetes cluster to manage its Kubernetes clusters. You run `kubectl get pods` and every single one says "Pending," like a waiting room in hell.',
    choices: [
      { label: 'Add the meta-cluster', result: 'It works. You are no longer sure what "simple" means as a concept, or ever did.', effects: { uptime: 6, sanity: -10 } },
      { label: 'Simplify back to a single cluster', result: 'Radical. Terrifying. Correct. Someone in the Kubernetes Slack calls you brave, unprompted.', effects: { sanity: 8, reputation: 6 } },
      { label: 'Just add more YAML', result: 'This is not a solution. This has never once, in the history of computing, been a solution.', effects: { sanity: -8, uptime: -3 } },
    ],
  },
  {
    id: 'the-vim-guy',
    minRank: 1,
    maxRank: 4,
    log: 'A colleague spends fifteen minutes of pair programming explaining why vim is objectively superior. He has not typed a single character in that time.',
    choices: [
      { label: 'Let him finish, nod along', result: 'He finishes. He is right, actually, but you will never admit it out loud, ever, to anyone.', effects: { sanity: -4, karma: 3 } },
      { label: 'Open VS Code out of spite, loudly', result: 'A silence falls over the room that has not been matched since the last outage.', effects: { karma: -3, sanity: 5 } },
      { label: 'Ask if he\'s tried the mouse', result: 'He looks at you the way people once looked at heretics.', effects: { karma: -2, sanity: 6 } },
    ],
  },
  {
    id: 'cloud-bill-shock',
    minRank: 1,
    maxRank: 5,
    log: 'This month\'s cloud bill is $41,000. Last month it was $9,000. Nobody shipped anything. Nothing changed. This is, somehow, both true and the entire problem.',
    choices: [
      { label: 'Dig into the billing dashboard yourself', result: 'You find a forgotten load test script that has been "load testing" production, alone, in the dark, for six weeks.', effects: { sanity: -8, reputation: 10, uptime: 4 } },
      { label: 'Forward it to finance and hope they don\'t ask questions', result: 'They ask questions. All of them. In a meeting. That you are now in.', effects: { sanity: -6, reputation: -6 } },
      { label: 'Blame a "traffic spike"', result: 'The traffic spike, like networking, is unable to defend itself, and also does not exist.', effects: { karma: -6, sanity: 4 } },
    ],
  },

  // ---------- Rank 3-5: Senior / Staff / Principal ----------
  {
    id: 'exec-status-report',
    minRank: 3,
    maxRank: 5,
    log: 'An exec wants a "quick" status update on infra health, in one slide, by end of day, containing eighteen months of nuance.',
    choices: [
      { label: 'Make the slide brutally honest', result: 'The slide is well received. Three follow-up meetings are scheduled to discuss the one slide.', effects: { reputation: 8, sanity: -8 } },
      { label: 'Make the slide look great', result: 'It looks great. It is not true. This will come up again, at the worst possible moment, as these things do.', effects: { karma: -8, sanity: 5 } },
      { label: 'Send the full postmortem doc instead of a slide', result: 'Bold. The exec reads the title, none of the content, and asks for the slide anyway.', effects: { sanity: 3, reputation: -3 } },
    ],
  },
  {
    id: 'headcount-freeze',
    minRank: 3,
    maxRank: 5,
    log: 'Finance announces a headcount freeze. Your team is now three people doing the work of six, and one of the three is you.',
    choices: [
      { label: 'Cut scope, protect the team', result: 'Fewer features ship. Nobody quits this quarter. You take the quiet, unglamorous win.', effects: { karma: 8, sanity: 4, reputation: -4 } },
      { label: 'Push the team to absorb the extra work', result: 'Everything ships on time. Everyone is quietly, actively looking at LinkedIn during standup.', effects: { uptime: 6, sanity: -12, karma: -6 } },
      { label: 'Escalate loudly to leadership', result: 'You get a "noted," a nod, and a calendar invite for three weeks from now that will get rescheduled twice.', effects: { reputation: 5, sanity: -5 } },
    ],
  },
  {
    id: 'acquisition-integration',
    minRank: 3,
    maxRank: 5,
    log: 'The company you just acquired uses a completely different stack, a different cloud provider, and, inexplicably, a different definition of "done." You now own the integration.',
    choices: [
      { label: 'Migrate them onto your stack', result: 'Six painful months later, one platform, mostly. You have earned the right to say "mostly" with real authority.', effects: { sanity: -10, reputation: 10, uptime: -4 } },
      { label: 'Run both stacks in parallel indefinitely', result: 'Nobody ever fully understands the whole system again. This is now, simply, how things are.', effects: { sanity: 4, uptime: -6 } },
      { label: 'Let them migrate onto their preferred tools instead', result: 'Everyone is happier. The vendor bill triples. You have traded morale for money, which is, historically, a popular trade.', effects: { karma: 6, sanity: 6, reputation: -4 } },
    ],
  },
  {
    id: 'board-asks-about-ai',
    minRank: 3,
    maxRank: 5,
    log: 'A board member asks if your infrastructure is "AI-native." Nobody in the room knows what that means, including the board member who asked it, with total confidence.',
    choices: [
      { label: 'Give a real, technical answer', result: 'You lose the room in the first sentence but keep your dignity, which is not nothing.', effects: { reputation: 6, sanity: -4 } },
      { label: 'Say "we\'re investing heavily in that direction"', result: 'This satisfies everyone and commits you to absolutely nothing, which is the entire skill of being an executive.', effects: { karma: -3, reputation: 4 } },
      { label: 'Actually go build something AI-native by next quarter', result: 'It ships. It is, generously, "fine." A chatbot now exists where a form used to be.', effects: { sanity: -15, reputation: 5 } },
    ],
  },
  {
    id: 'agent-vault-style-decision',
    minRank: 3,
    maxRank: 5,
    tag: 'security',
    log: 'A new internal agent needs a GitHub token and a model API key to do its job. Someone suggests just dropping both into its .env, "just for now," a phrase with a body count.',
    choices: [
      { label: 'Broker the credentials through a proxy instead, so the agent never holds real ones', result: 'More setup up front. The agent could read every file in the repo and still have nothing worth stealing.', effects: { sanity: -4, reputation: 10, uptime: 2 } },
      { label: 'Just put them in the .env, ship it today', result: 'It works fine for weeks. "Fine for weeks" is exactly the sentence every incident report starts with.', effects: { sanity: 6, reputation: -6 } },
      { label: 'Scope the token narrowly and call it a day', result: 'Better than nothing. If it leaks, at least it leaks less, like a smaller hole in a still-sinking boat.', effects: { sanity: 3, reputation: 3, karma: 2 } },
    ],
  },
  {
    id: 'skill-marketplace-warning',
    minRank: 3,
    maxRank: 5,
    tag: 'security',
    log: 'A teammate wants to install a slick third-party "agent skill" from a marketplace to save time. It has four stars and a description written entirely in exclamation points.',
    choices: [
      { label: 'Review what it actually does before installing', result: 'It requests far more access than the task needs. You quietly decline for the whole org and feel briefly heroic.', effects: { sanity: -3, reputation: 8, karma: 3 } },
      { label: 'Install it, it saves so much time', result: 'It does save time. It also phones home more than it should, to somewhere you cannot pronounce.', effects: { sanity: 4, uptime: -8, reputation: -4 } },
      { label: 'Ban all third-party skills company-wide', result: 'Very safe. Also, morale takes a small, grumbling hit, mostly from the person with the four-star skill.', effects: { karma: -4, sanity: 6 } },
    ],
  },
  {
    id: 'principal-roadmap-review',
    minRank: 4,
    maxRank: 5,
    log: 'You are asked to review the entire company roadmap for infrastructure risk. It is 80 slides. Slide 43 is a stock photo of people high-fiving in front of a server rack.',
    choices: [
      { label: 'Read all 80 slides carefully', result: 'You find 6 real risks. Nobody acts on 5 of them. The stock photo remains the most impactful slide.', effects: { sanity: -12, reputation: 10 } },
      { label: 'Skim it and flag the biggest risk only', result: 'Efficient. You miss a smaller risk that becomes, verbatim, next quarter\'s incident title.', effects: { sanity: 4, uptime: -5 } },
      { label: 'Delegate the review to your team', result: 'They do a better job than you would have. You take the credit anyway, as tradition demands.', effects: { reputation: 6, karma: -5 } },
    ],
  },
  {
    id: 'company-collapse-rumor',
    minRank: 3,
    maxRank: 5,
    log: 'Rumors spread that the company is running out of runway. Nobody official confirms or denies it. The office wifi traffic to job boards has quadrupled overnight.',
    choices: [
      { label: 'Quietly start updating your resume', result: 'Practical. You are not the only one; you can hear the collective clicking of "Easy Apply" through the walls.', effects: { sanity: 6, karma: -2 } },
      { label: 'Double down and try to ship something that matters', result: 'Either this saves the company a little, or it saves nothing and you\'re exhausted either way. You do it anyway.', effects: { sanity: -10, reputation: 10 } },
      { label: 'Ask leadership directly in an all-hands', result: 'The answer is a very long pause, a sip of water, and "let\'s take that offline," which everyone knows means never.', effects: { reputation: 4, sanity: -6 } },
    ],
  },
  {
    id: 'principal-mentoring',
    minRank: 4,
    maxRank: 5,
    log: 'A junior engineer asks you to explain the entire deploy pipeline "in like five minutes." You have never explained it in under forty.',
    choices: [
      { label: 'Actually try to do it in five minutes', result: 'You fail spectacularly, run out of whiteboard, and both of you learn something real about the pipeline and yourselves.', effects: { sanity: -3, karma: 6 } },
      { label: 'Book a real hour and do it properly', result: 'They now understand it better than half the senior team, several of whom have been here longer than the pipeline itself.', effects: { sanity: -6, karma: 8, reputation: 4 } },
      { label: 'Send them the (outdated) wiki page', result: 'The wiki page describes a system that was replaced two migrations ago. This will cause problems in six months, with your name on the blast radius.', effects: { karma: -4, sanity: 4 } },
    ],
  },
  {
    id: 'cto-budget-cut',
    minRank: 5,
    log: 'As CTO, you must cut 20% of the infra budget this quarter. Everything is "critical." Everything is always "critical." Nothing has ever not been "critical."',
    choices: [
      { label: 'Cut the vendor nobody remembers approving', result: 'Someone remembers. It was load-bearing. Briefly, spectacularly, everything is on fire, and you did this.', effects: { uptime: -10, sanity: -6, reputation: -4 } },
      { label: 'Cut headcount instead of tools', result: 'The board loves this slide. Your team does not love you this quarter, or possibly ever again.', effects: { reputation: 8, karma: -15, sanity: -8 } },
      { label: 'Negotiate a smaller cut with real data', result: 'It takes three meetings and a spreadsheet nobody asked for but everyone secretly needed.', effects: { sanity: -8, reputation: 10 } },
    ],
  },
  {
    id: 'cto-postmortem-culture',
    minRank: 5,
    log: 'As CTO, you get to decide once and for all: are postmortems actually blameless here, or just called that, the way "unlimited PTO" is "unlimited."',
    choices: [
      { label: 'Make them genuinely blameless, enforce it personally', result: 'People start telling the truth in postmortems. This is rarer, and more valuable, than it has any right to be.', effects: { karma: 12, reputation: 8, sanity: -4 } },
      { label: 'Keep saying "blameless" while everyone knows better', result: 'Efficient hypocrisy. It has worked so far, in the sense that nothing has technically exploded yet.', effects: { karma: -10, sanity: 4 } },
      { label: 'Cancel postmortems, they take too long', result: 'The same outages start repeating, now with dramatically less paperwork and dramatically more déjà vu.', effects: { uptime: -10, karma: -6 } },
    ],
  },
  {
    id: 'cto-agent-rollout',
    minRank: 5,
    tag: 'security',
    log: 'As CTO, you approve a company-wide rollout of AI agents with real access to internal tools. Someone in the Slack thread types "what could go wrong" with no punctuation, which is somehow the most alarming part.',
    choices: [
      { label: 'Insist every agent\'s credentials are brokered, none held directly', result: 'It costs a slower rollout. It also means a compromised agent has nothing real to hand over, ever, to anyone.', effects: { sanity: -5, reputation: 12, uptime: 4 } },
      { label: 'Let each team wire up credentials however they want', result: 'Rollout is fast. So, eventually, and predictably, is the incident.', effects: { sanity: 6, reputation: -8, uptime: -6 } },
      { label: 'Approve it, review security "later"', result: '"Later" arrives during an incident review, which is, historically, the worst possible time for "later" to arrive.', effects: { karma: -6, uptime: -8 } },
    ],
  },
]
